# Generated by Django 2.2.5 on 2019-11-29 03:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '分類',
                'verbose_name_plural': '分類',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '重要度',
                'verbose_name_plural': '重要度',
                'db_table': 'Ranks',
            },
        ),
        migrations.CreateModel(
            name='Suitoh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('out_cost', models.IntegerField(verbose_name='支出')),
                ('meimoku', models.CharField(max_length=100, verbose_name='名目')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo_tuto.Category', verbose_name='分類')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo_tuto.Ranks', verbose_name='重要度')),
            ],
            options={
                'verbose_name': '出納表',
                'verbose_name_plural': '出納表',
                'db_table': 'suitoh',
            },
        ),
    ]
